CREATE TABLE users (
	user_id INT AUTO_INCREMENT,
	name VARCHAR(50),
	address VARCHAR(50),
	dob DATE,
	status_user SMALLINT,
	gender CHAR,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_USER PRIMARY KEY(user_id)
);

CREATE TABLE product_types (
	type_id INT AUTO_INCREMENT,
	detail VARCHAR(50),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_TYPE PRIMARY KEY(type_id)

);

CREATE TABLE product_description (
	product_id INT(11),
	description TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT product_description_fk FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE operators (
	operator_id INT AUTO_INCREMENT,
	name VARCHAR(50),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_OPERATOR PRIMARY KEY(operator_id)
);

CREATE TABLE payment_methods (
	payment_id INT AUTO_INCREMENT,
	name VARCHAR(50),
	status_type SMALLINT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_PAYMENT PRIMARY KEY(payment_id)
);

CREATE TABLE products (
	product_id INT AUTO_INCREMENT,
	product_name VARCHAR(50),
	product_type INT,
	product_description TEXT,
	operator INT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_PRODUCT PRIMARY KEY(product_id),
	CONSTRAINT FK_TYPE FOREIGN KEY (product_type) REFERENCES product_types(type_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_OPERATOR FOREIGN KEY (operator) REFERENCES operators(operator_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE transactions (
	transaction_id INT AUTO_INCREMENT,
	user_id INT,
	payment_id INT,
	status VARCHAR(10),
	total INT,
	total_qty INT(11),
	total_price NUMERIC(25,2),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_TX PRIMARY KEY(transaction_id),
	CONSTRAINT FK_USER FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_PAYID FOREIGN KEY (payment_id) REFERENCES payment_methods(payment_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE transaction_details (
	transaction_id INT, 
	product_id INT,
	status VARCHAR(10),
	qty INT,,
	price NUMERIC(25,2),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT FK_TXID FOREIGN KEY (transaction_id) REFERENCES transactions(transaction_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_PRODUCTID FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE CASCADE ON UPDATE CASCADE
);